// @ts-nocheck
/* eslint-disable */
import { useState, useMemo, useEffect, useCallback } from 'react';
import { Card, CardHeader } from '../components/ui/Card';
import { Select } from '../components/ui/Select';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { DataTable } from '../components/ui/Table';
import { Tabs, TabContent } from '../components/ui/Tabs';
import { PercentChangeBadge, StatusBadge } from '../components/ui/Badge';
import { Heatmap } from '../components/charts/Heatmap';
import { Filter, Loader2 } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, LineChart, Line, ScatterChart, Scatter, XAxis, YAxis, CartesianGrid, Tooltip, Legend, Cell, ComposedChart } from 'recharts';
import { utcToVN, parseUtcMs, getTodayVN, normalizeSignalDates } from '../utils/time';
import { signalsApi, type SignalsOverviewRequest, type GroupPerformanceRequest } from '../services/signalsApi';

const API = '/api';
const VN_MS = 7 * 3600 * 1000;
const TABS = [{id:'performance',label:'Performance'},{id:'heatmap',label:'Heatmap Matri?'},{id:'score',label:'Score Analysis'},{id:'correlation',label:'Feature Correlation'},{id:'indicators',label:'Indicator Analysis'},{id:'trades',label:'Trade List'}];
const COLORS = ['#6366f1','#10b981','#f59e0b','#ef4444','#8b5cf6','#06b6d4','#ec4899'];

/** Convert exit_time UTC -> VN date string "YYYY-MM-DD" */
function exitToVNDate(exitTime) {
  if (!exitTime) return '';
  const ms = parseUtcMs(exitTime);
  if (!ms) return '';
  const vn = new Date(ms + VN_MS);
  return `${vn.getUTCFullYear()}-${String(vn.getUTCMonth()+1).padStart(2,'0')}-${String(vn.getUTCDate()).padStart(2,'0')}`;
}

function ScoreCell({ value }) { const v = Number(value) || 0; return <span className={`font-mono text-sm ${v >= 8 ? 'text-emerald-400' : v >= 6 ? 'text-yellow-400' : 'text-red-400'}`}>{v.toFixed(2)}</span>; }
function ChartTT({ active, payload, label }) { if (!active || !payload?.length) return null; return (<div className="bg-slate-800 border border-slate-600 rounded-lg p-3 shadow-xl text-sm"><p className="text-yellow-400 font-semibold mb-1">{label}</p>{payload.map((e, i) => (<div key={i} className="flex items-center gap-2"><div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: e.color }} /><span className="text-white">{e.name}: <strong>{typeof e.value === 'number' ? e.value.toFixed(2) : e.value}</strong></span></div>))}</div>); }
const isInfiniteMetric = (v) => !Number.isFinite(Number(v)) || Number(v) >= 1000000000;
async function fetchQ(query, params = {}) { const res = await fetch(`${API}/signal-analysis`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, params }) }); if (!res.ok) return []; const json = await res.json(); return json.data || []; }

export function Signals() {
  const today = getTodayVN();
  const [tab, setTab] = useState('performance'); const [loading, setLoading] = useState(true); const [overviewData, setOverviewData] = useState(null); const [groupPerfData, setGroupPerfData] = useState([]); const [heatmapData, setHeatmapData] = useState([]); const [tradesData, setTradesData] = useState({data:[],total:0,page:1,limit:20,pages:1}); const [ad, setAd] = useState({}); const [loadedTabs, setLoadedTabs] = useState(new Set());
  const [strategies, setStrategies] = useState([]); const [patterns, setPatterns] = useState([]); const [engineVersions, setEngineVersions] = useState([]); const [fetchingTop50, setFetchingTop50] = useState(false);
  const [f, setF] = useState({ capital:10000,posSize:1000,startDate:'',endDate:'',symbols:'',symbolMode:'include',scoreMin:0,scoreMax:10,engineVersion:'all',engineMode:'only',timeframes:[],strategies:[],patterns:[],regimes:[],directions:[] });
  const [applied, setApplied] = useState({...f}); const set = (k,v) => setF(prev=>({...prev,[k]:v})); const toggleArr = (k,v) => setF(prev=>{const arr=prev[k]; return {...prev,[k]:arr.includes(v)?arr.filter(x=>x!==v):[...arr,v]};});
  const [groupBy, setGroupBy] = useState('pattern');
  const [tradesPage, setTradesPage] = useState(1);
  // Reason grouping for Block Reason Analysis
  const [selectedReasonGroup, setSelectedReasonGroup] = useState('all');

  // For /api/signal-analysis endpoint — send plain VN date, backend handles conversion
  const getAnalysisParams = useCallback(()=>{
    const p = {};
    if (applied.startDate) p.start_date = applied.startDate;
    if (applied.endDate) p.end_date = applied.endDate;
    if (applied.symbols?.trim()) { p.symbols = applied.symbols; p.symbol_mode = applied.symbolMode; }
    if (applied.timeframes?.length) p.timeframes = applied.timeframes;
    if (applied.strategies?.length) p.strategies = applied.strategies;
    if (applied.patterns?.length) p.patterns = applied.patterns;
    if (applied.regimes?.length) p.regimes = applied.regimes;
    if (applied.directions?.length) p.directions = applied.directions;
    if (applied.engineVersion !== 'all') { p.engine_version = applied.engineVersion; p.engine_mode = applied.engineMode; }
    if (applied.scoreMin > 0) p.score_min = applied.scoreMin;
    if (applied.scoreMax < 10) p.score_max = applied.scoreMax;
    return p;
  },[applied]);

  const loadBase = useCallback(async()=>{setLoading(true);try{const ap=getAnalysisParams();const[versRes,options,funnel,block_reasons,overview]=await Promise.all([fetch(`${API}/engine/versions`).then(r=>r.json()).catch(()=>[]),fetch(`${API}/filter-options`).then(r=>r.json()).catch(()=>({strategies:[],patterns:[]})),fetchQ('funnel',ap).catch(()=>[]),fetchQ('block_reasons',ap).catch(()=>[]),signalsApi.fetchOverview({...ap,initial_capital:applied.capital,position_size:applied.posSize}).catch(()=>null)]);setEngineVersions(versRes.map(v=>String(v.engine_version)).filter(Boolean).sort().reverse());setStrategies(options.strategies||[]);setPatterns(options.patterns||[]);setAd({funnel,block_reasons});setOverviewData(overview);setLoadedTabs(new Set(['performance']));}catch(e){console.error(e);}finally{setLoading(false);};},[getAnalysisParams,applied.capital,applied.posSize]);

  const TAB_QUERIES = {performance:['block_reasons'],heatmap:['score_regime_heatmap','component_heatmap','rsi_vol_heatmap','tf_symbol_heatmap','atr_score_heatmap','mtf_trend_heatmap'],score:['score_histogram','score_scatter','score_calibration','score_threshold_optimizer','score_component_radar','score_quality_trend'],correlation:['feature_correlation','feature_importance_full'],indicators:['exit_reason_breakdown','time_to_exit_dist','mae_mfe_scatter']};

  const loadTabData = useCallback(async(tabId)=>{if(loadedTabs.has(tabId)||tabId==='trades')return;const dp=getAnalysisParams();const queries=TAB_QUERIES[tabId]||[];try{const results=await Promise.all(queries.map(q=>fetchQ(q,dp).catch(err=>{console.error('query fail',q,err);return[];})));const obj={};queries.forEach((q,i)=>{if(q==='mae_mfe_scatter')obj['maeMfe']=results[i];else obj[q]=results[i];});if(tabId==='indicators'){obj['indRsi']=await fetchQ('indicator_bucket',{...dp,indicator:'rsi'}).catch(()=>[]);obj['indVol']=await fetchQ('indicator_bucket',{...dp,indicator:'volume_ratio'}).catch(()=>[]);obj['indAtr']=await fetchQ('indicator_bucket',{...dp,indicator:'atr_percentile'}).catch(()=>[]);}setAd(prev=>({...prev,...obj}));setLoadedTabs(prev=>new Set([...prev,tabId]));}catch(e){console.error('Tab load failed',tabId,e);};},[loadedTabs,getAnalysisParams]);

  // Load backend aggregate data when filter changes
  useEffect(()=>{if(!loading){const dp=getAnalysisParams();Promise.all([signalsApi.fetchGroupPerformance({...dp,group_by:groupBy}).then(r=>setGroupPerfData(r.groups||[])).catch(()=>[]),signalsApi.fetchHeatmaps(dp).then(r=>setHeatmapData(r.pattern_timeframe||[])).catch(()=>[]),signalsApi.fetchTrades({...dp,page:tradesPage,limit:20,search_symbols:'',sort_by:'exit_time',sort_order:'desc'}).then(r=>setTradesData(r)).catch(()=>setTradesData({data:[],total:0,page:1,limit:20,pages:1}))]).catch(e=>console.error('Backend load failed',e));};},[loading,applied,groupBy,tradesPage,getAnalysisParams]);

  useEffect(()=>{loadBase();},[loadBase]); useEffect(()=>{if(!loading)loadTabData(tab);},[tab,loading,loadTabData]);

  const fetchTop50 = async () => { setFetchingTop50(true); try { const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false', { headers: { 'x-cg-demo-api-key': 'CG-r9KNtFCb794fJuozcK1AMr2W' } }); const coins = await res.json(); set('symbols', coins.map(c => c.symbol.toUpperCase()).join(' ')); } catch (e) { console.error(e); } finally { setFetchingTop50(false); } };

  // KPI from backend overview
  const kpi = useMemo(()=>{if(!overviewData)return{nav:applied.capital,total:0,scanned:0,wr:0,pf:0,exp:0,corr:0};return{nav:overviewData.nav,total:overviewData.total,scanned:overviewData.scanned,wr:overviewData.win_rate,pf:overviewData.profit_factor,exp:overviewData.expectancy,corr:overviewData.score_return_corr};},[overviewData,applied.capital]);

  const $=v=>v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  const tradeColumns = [{key:'symbol',header:'Symbol',sortable:true},{key:'direction',header:'Dir',sortable:true,render:v=><span className={`text-xs font-bold ${v==='LONG'?'text-emerald-400':'text-red-400'}`}>{v==='LONG'?'▲L':'▼S'}</span>},{key:'timeframe',header:'TF',sortable:true},{key:'pattern',header:'Pattern',sortable:true,render:v=><span className="text-[11px]">{v}</span>},{key:'score',header:'Score',sortable:true,render:v=><ScoreCell value={v} />},{key:'entry_price',header:'Entry',render:v=>v?.toFixed(v>100?2:4)||'-'},{key:'result_percent',header:'P&L',sortable:true,render:v=><PercentChangeBadge value={v||0} />},{key:'status',header:'Status',sortable:true,render:v=><StatusBadge status={v} />},{key:'regime',header:'Regime',sortable:true,render:v=><span className="text-xs">{v==='SIDEWAYS'?'SW':v}</span>},{key:'strategy_name',header:'Strategy',sortable:true,render:v=><span className="text-[11px]">{v}</span>},{key:'exit_time',header:'Closed',sortable:true,render:v=><span className="text-[11px] text-slate-400">{utcToVN(v)}</span>}];

  // Use backend group performance data
  const perfData = useMemo(()=>{return groupPerfData.map(g=>({name:g.name,trades:g.trades,wins:g.wins,losses:g.losses,winrate:g.winrate,pf:g.profit_factor,avgReturn:g.avg_return})).sort((a,b)=>b.winrate-a.winrate);},[groupPerfData]);

  if(loading)return<div className="flex items-center justify-center h-96"><Loader2 className="w-8 h-8 animate-spin text-indigo-500" /></div>;

  return(
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-white">Signal Analysis</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-6 gap-3"><Card className="p-3 text-center"><p className="text-xs text-slate-400">Final NAV</p><p className={`text-lg font-bold ${kpi.nav>=applied.capital?'text-emerald-400':'text-red-400'}`}>${$(kpi.nav)}</p></Card><Card className="p-3 text-center"><p className="text-xs text-slate-400">Traded / Scanned</p><p className="text-lg font-bold text-white">{kpi.total} / {kpi.scanned}</p></Card><Card className="p-3 text-center"><p className="text-xs text-slate-400">Win Rate</p><p className={`text-lg font-bold ${kpi.wr>=50?'text-emerald-400':'text-red-400'}`}>{kpi.wr.toFixed(1)}%</p></Card><Card className="p-3 text-center"><p className="text-xs text-slate-400">Profit Factor</p><p className="text-lg font-bold text-white">{isInfiniteMetric(kpi.pf)?'Infinity':kpi.pf.toFixed(2)}</p></Card><Card className="p-3 text-center"><p className="text-xs text-slate-400">Expectancy</p><p className={`text-lg font-bold ${kpi.exp>=0?'text-emerald-400':'text-red-400'}`}>{kpi.exp.toFixed(2)}%</p></Card><Card className="p-3 text-center"><p className="text-xs text-slate-400">Score to Return</p><p className={`text-lg font-bold ${kpi.corr>0?'text-emerald-400':'text-red-400'}`}>{kpi.corr.toFixed(3)}</p></Card></div>

      <Card><div className="flex items-center gap-2 mb-4"><Filter className="w-4 h-4 text-slate-400" /><span className="text-sm font-semibold text-white">Filters</span></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-10 gap-3 mb-4">
          <div><Input type="number" label="Capital ($)" value={f.capital} onChange={e=>set('capital',Number(e.target.value)||10000)} /></div>
          <div><Input type="number" label="Position ($)" value={f.posSize} onChange={e=>set('posSize',Number(e.target.value)||1000)} /></div>
          <div><Input type="date" label="Start" value={f.startDate} onChange={e=>set('startDate',e.target.value)} /></div>
          <div><Input type="date" label="End" value={f.endDate} onChange={e=>set('endDate',e.target.value)} /></div>
          <div className="sm:col-span-2"><label className="block text-sm font-medium text-slate-400 mb-1.5">Symbol</label><div className="flex gap-1"><input type="text" value={f.symbols} onChange={e=>set('symbols',e.target.value)} placeholder="BTC ETH SOL..." className="flex-1 bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm" /><button onClick={()=>set('symbolMode',f.symbolMode==='include'?'exclude':'include')} className={`px-3 py-2 rounded-lg text-xs font-bold ${f.symbolMode==='include'?'bg-emerald-600 text-white':'bg-red-600 text-white'}`}>{f.symbolMode==='include'?'Include':'Exclude'}</button><button onClick={fetchTop50} disabled={fetchingTop50} className="px-2 py-2 bg-yellow-600 hover:bg-yellow-500 text-white rounded-lg text-xs">{fetchingTop50?'...':'Top50'}</button></div></div>
          <div><label className="block text-sm font-medium text-slate-400 mb-1.5">Engine</label><div className="flex gap-1"><select value={f.engineVersion} onChange={e=>set('engineVersion',e.target.value)} className="flex-1 bg-slate-800 border border-slate-600 rounded-lg px-3 py-2 text-white text-sm"><option value="all">All</option>{engineVersions.map(v=><option key={v} value={v}>v{v}</option>)}</select><button onClick={()=>set('engineMode',f.engineMode==='only'?'newest':f.engineMode==='newest'?'older':'only')} className={`px-3 py-2 rounded-lg text-xs font-bold ${f.engineMode!=='only'?'bg-indigo-600 text-white':'bg-slate-700 text-slate-400'}`}>{f.engineMode==='only'?'Only':f.engineMode==='newest'?'+New':'+Old'}</button></div></div>
          <div className="sm:col-span-2"><label className="block text-sm font-medium text-slate-400 mb-1.5">Score {f.scoreMin.toFixed(1)} - {f.scoreMax.toFixed(1)}</label><input type="range" min={0} max={10} step={0.5} value={f.scoreMin} onChange={e=>set('scoreMin',Number(e.target.value))} className="w-full accent-indigo-500 h-1.5" /><input type="range" min={0} max={10} step={0.5} value={f.scoreMax} onChange={e=>set('scoreMax',Number(e.target.value))} className="w-full accent-indigo-500 h-1.5" /></div>
          <div className="flex items-end"><Button variant="primary" className="w-full" onClick={()=>{setApplied({...f});setLoadedTabs(new Set());setAd(prev=>({funnel:prev.funnel,block_reasons:prev.block_reasons}));}}>Apply</Button></div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-12 gap-4 pt-3 border-t border-slate-700">
          <div className="sm:col-span-1"><p className="text-[10px] text-slate-500 uppercase font-semibold mb-1.5">Timeframe</p><div className="flex gap-1">{['15m','1h','4h'].map(tf=><button key={tf} onClick={()=>toggleArr('timeframes',tf)} className={`px-2.5 py-1.5 rounded text-xs ${f.timeframes.includes(tf)?'bg-indigo-600 text-white':'bg-slate-700 text-slate-400'}`}>{tf}</button>)}</div></div>
          <div className="sm:col-span-2"><p className="text-[10px] text-slate-500 uppercase font-semibold mb-1.5">Strategy</p><div className="flex gap-1 flex-wrap">{strategies.map(s=><button key={s} onClick={()=>toggleArr('strategies',s)} className={`px-2 py-1 rounded text-xs ${f.strategies.includes(s)?'bg-indigo-600 text-white':'bg-slate-700 text-slate-400'}`}>{s}</button>)}</div></div>
          <div className="sm:col-span-5"><p className="text-[10px] text-slate-500 uppercase font-semibold mb-1.5">Pattern</p><div className="flex gap-1 flex-wrap">{patterns.map(p=><button key={p} onClick={()=>toggleArr('patterns',p)} className={`px-2 py-1 rounded text-xs ${f.patterns.includes(p)?'bg-indigo-600 text-white':'bg-slate-700 text-slate-400'}`}>{p}</button>)}</div></div>
          <div className="sm:col-span-2"><p className="text-[10px] text-slate-500 uppercase font-semibold mb-1.5">Regime</p><div className="flex gap-1 flex-wrap">{['BULL','BEAR','SIDEWAYS'].map(r=><button key={r} onClick={()=>toggleArr('regimes',r)} className={`px-2 py-1 rounded text-xs ${f.regimes.includes(r)?'bg-indigo-600 text-white':'bg-slate-700 text-slate-400'}`}>{r}</button>)}</div></div>
          <div className="sm:col-span-2"><p className="text-[10px] text-slate-500 uppercase font-semibold mb-1.5">Direction</p><div className="flex gap-1 flex-wrap">{['LONG','SHORT'].map(d=><button key={d} onClick={()=>toggleArr('directions',d)} className={`px-2 py-1 rounded text-xs ${f.directions.includes(d)?'bg-indigo-600 text-white':'bg-slate-700 text-slate-400'}`}>{d}</button>)}</div></div>
        </div>
      </Card>

      <Tabs tabs={TABS} activeTab={tab} onChange={setTab} variant="underline" />
      <TabContent>
        {tab==='performance'&&(<div className="space-y-6"><div className="flex items-center gap-4"><Select label="Group by" value={groupBy} onChange={setGroupBy} options={[{value:'pattern',label:'Pattern'},{value:'direction',label:'Direction'},{value:'regime',label:'Regime'},{value:'timeframe',label:'Timeframe'},{value:'strategy_name',label:'Strategy'},{value:'score',label:'Score'},{value:'engine_version',label:'Engine'}]} className="w-48" /></div>
        <Card><CardHeader title="Win Rate by Group" />{perfData.length>0?<ResponsiveContainer width="100%" height={300}><BarChart data={perfData}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="name" stroke="#64748b" fontSize={11} /><YAxis stroke="#64748b" fontSize={11} /><Tooltip content={<ChartTT />} /><Bar dataKey="winrate" name="Win Rate %" radius={[4,4,0,0]}>{perfData.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]} />)}</Bar></BarChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Group Performance" /><DataTable columns={[{key:'name',header:groupBy,sortable:true},{key:'trades',header:'Trades',sortable:true,align:'right'},{key:'wins',header:'Wins',sortable:true,align:'right',render:v=><span className="text-emerald-400">{v}</span>},{key:'losses',header:'Losses',sortable:true,align:'right',render:v=><span className="text-red-400">{v}</span>},{key:'winrate',header:'WR%',sortable:true,align:'right',render:v=><span className={v>=50?'text-emerald-400':'text-red-400'}>{v.toFixed(1)}%</span>},{key:'pf',header:'PF',sortable:true,align:'right',render:v=>isInfiniteMetric(v)?'∞':v.toFixed(2)},{key:'avgReturn',header:'Avg Return',sortable:true,render:v=><PercentChangeBadge value={v} />}]} data={perfData} pageSize={15} /></Card>
        <Card><CardHeader title="Signal Quality Funnel" subtitle="Based on scan_debug date range" />{ad.funnel?.length?<div className="space-y-2 py-4">{ad.funnel.map((row,i)=>{const max=Number(ad.funnel[0]?.count)||1;const pct=((Number(row.count)/max)*100).toFixed(1);return<div key={i} className="flex items-center gap-4"><span className="w-32 text-sm text-slate-400 text-right">{row.stage}</span><div className="flex-1 bg-slate-800 rounded-full h-8 overflow-hidden"><div className="h-full bg-indigo-500/70 rounded-full flex items-center px-3" style={{width:`${Math.max(Number(pct),5)}%`}}><span className="text-xs text-white font-medium whitespace-nowrap">{Number(row.count).toLocaleString()} ({pct}%)</span></div></div></div>})}</div>:<div className="h-32 flex items-center justify-center text-slate-500">No scan data in date range</div>}</Card>
        <Card><CardHeader title="Block Reason Analysis" subtitle="HTF* grouped" />{ad.block_reasons?.length?<DataTable columns={[{key:'reason',header:'Reason',sortable:true},{key:'n',header:'Count',sortable:true,align:'right'},{key:'pct',header:'%',sortable:true,align:'right',render:v=>`${v}%`},{key:'avg_score',header:'Avg Score',sortable:true,align:'right'}]} data={ad.block_reasons} pageSize={10} />:<div className="h-32 flex items-center justify-center text-slate-500">No data</div>}</Card></div>)}

        {tab==='heatmap'&&(<div className="space-y-6"><Card><CardHeader title="Pattern x Timeframe" />{heatmapData.length?<Heatmap data={heatmapData} xLabel="TF" yLabel="Pattern" valueLabel="WR%" colorScale="green-red" showValues />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card><Card><CardHeader title="Score x Regime -> Win Rate" />{ad.score_regime_heatmap?.length?<Heatmap data={ad.score_regime_heatmap.map(r=>({x:r.regime,y:r.score_band,value:Number(r.win_rate)||50,count:Number(r.n_trades)||0}))} xLabel="Regime" yLabel="Score" valueLabel="WR%" colorScale="green-red" showValues />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card><Card><CardHeader title="Component Score x Win Rate" />{ad.component_heatmap?.length?<Heatmap data={ad.component_heatmap.map(r=>({x:String(Number(r.bucket).toFixed(1)),y:r.component,value:Number(r.win_rate)||50,count:Number(r.n)||0}))} xLabel="Bucket" yLabel="Component" valueLabel="WR%" colorScale="green-red" showValues />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card><Card><CardHeader title="RSI x Volume Ratio -> Win Rate" />{ad.rsi_vol_heatmap?.length?<Heatmap data={ad.rsi_vol_heatmap.map(r=>({x:r.vol_zone,y:r.rsi_zone,value:Number(r.win_rate)||50,count:Number(r.n_trades)||0}))} xLabel="Volume" yLabel="RSI" valueLabel="WR%" colorScale="green-red" showValues />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><CardHeader title="Symbol x Timeframe" />{ad.tf_symbol_heatmap?.length?<Heatmap data={ad.tf_symbol_heatmap.map(r=>({x:r.timeframe,y:r.symbol,value:Number(r.win_rate)||50,count:Number(r.n_trades)||0}))} xLabel="Timeframe" yLabel="Symbol" valueLabel="WR%" colorScale="green-red" showValues />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card><div className="space-y-6"><Card><CardHeader title="ATR x Score Heatmap" />{ad.atr_score_heatmap?.length?<Heatmap data={ad.atr_score_heatmap.map(r=>({x:r.score_band,y:r.atr_bucket,value:Number(r.win_rate)||50,count:Number(r.n_trades)||0}))} xLabel="Score" yLabel="ATR%" valueLabel="WR%" colorScale="green-red" showValues />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card><Card><CardHeader title="MTF x Trend Heatmap" />{ad.mtf_trend_heatmap?.length?<Heatmap data={ad.mtf_trend_heatmap.map(r=>({x:r.trend_bucket,y:r.mtf_bucket,value:Number(r.win_rate)||50,count:Number(r.n_trades)||0}))} xLabel="Trend" yLabel="MTF" valueLabel="WR%" colorScale="green-red" showValues />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card></div></div></div>)}

        {tab==='score'&&(<div className="space-y-6"><Card><CardHeader title="Score Histogram - Wins vs Losses + Win Rate" />{ad.score_histogram?.length?<ResponsiveContainer width="100%" height={300}><ComposedChart data={ad.score_histogram}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="score_bucket" stroke="#64748b" fontSize={11} /><YAxis yAxisId="left" stroke="#64748b" fontSize={11} /><YAxis yAxisId="right" orientation="right" stroke="#eab308" fontSize={11} tickFormatter={v=>`${v}%`} /><Tooltip content={<ChartTT />} /><Legend /><Bar yAxisId="left" dataKey="wins" name="Wins" fill="#10b981" radius={[4,4,0,0]} /><Bar yAxisId="left" dataKey="losses" name="Losses" fill="#ef4444" radius={[4,4,0,0]} /><Line yAxisId="right" type="monotone" dataKey="win_rate" name="Win Rate %" stroke="#eab308" strokeWidth={2} dot={{r:3}} /></ComposedChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Score to Return Analysis" subtitle="Average return by score range" />{ad.score_histogram?.length?<ResponsiveContainer width="100%" height={250}><BarChart data={ad.score_histogram}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="score_bucket" stroke="#64748b" fontSize={11} /><YAxis stroke="#64748b" fontSize={11} tickFormatter={v=>`${v}%`} /><Tooltip content={<ChartTT />} /><Bar dataKey="avg_return" name="Avg Return %" radius={[4,4,0,0]}>{ad.score_histogram.map((e,i)=><Cell key={i} fill={Number(e.avg_return)>=0?'#10b981':'#ef4444'} />)}</Bar></BarChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Score Threshold Optimizer" subtitle="Which min score gives best resultsx" />{ad.score_threshold_optimizer?.length?<ResponsiveContainer width="100%" height={300}><ComposedChart data={ad.score_threshold_optimizer}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="threshold" stroke="#64748b" fontSize={11} /><YAxis yAxisId="left" stroke="#64748b" fontSize={11} /><YAxis yAxisId="right" orientation="right" stroke="#eab308" fontSize={11} tickFormatter={v=>`${v}%`} /><Tooltip content={<ChartTT />} /><Legend /><Bar yAxisId="left" dataKey="n_trades" name="Trades" fill="#334155" /><Line yAxisId="right" type="monotone" dataKey="win_rate" name="Win Rate %" stroke="#eab308" strokeWidth={2} dot={{r:3}} /><Line yAxisId="right" type="monotone" dataKey="avg_return" name="Avg Return %" stroke="#6366f1" strokeWidth={2} dot={{r:3}} /></ComposedChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Score Calibration Curve" />{ad.score_calibration?.length?<ResponsiveContainer width="100%" height={250}><LineChart data={ad.score_calibration}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="score_mean" stroke="#64748b" fontSize={11} /><YAxis stroke="#64748b" fontSize={11} tickFormatter={v=>`${v}%`} /><Tooltip content={<ChartTT />} /><Line type="monotone" dataKey="actual_win_rate" name="Win Rate" stroke="#6366f1" strokeWidth={2} dot={{r:4}} /></LineChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Score Component Breakdown" />{ad.score_component_radar?.length?<DataTable columns={[{key:'score_band',header:'Band'},{key:'avg_trend',header:'Trend',align:'right'},{key:'avg_momentum',header:'Mom',align:'right'},{key:'avg_volume',header:'Vol',align:'right'},{key:'avg_pattern',header:'Pat',align:'right'},{key:'avg_mtf',header:'MTF',align:'right'},{key:'avg_penalty',header:'Pen',align:'right'},{key:'win_rate',header:'WR%',align:'right',render:v=><span className={v>=50?'text-emerald-400':'text-red-400'}>{v}%</span>},{key:'n',header:'N',align:'right'}]} data={ad.score_component_radar} pageSize={5} />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Score to Return Scatter" />{ad.score_scatter?.length?<ResponsiveContainer width="100%" height={300}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis type="number" dataKey="total_score" name="Score" stroke="#64748b" fontSize={11} /><YAxis type="number" dataKey="trade_return" name="Return %" stroke="#64748b" fontSize={11} /><Tooltip content={<ChartTT />} /><Scatter data={ad.score_scatter.filter(r=>r.label===1)} fill="#10b981" name="Win" /><Scatter data={ad.score_scatter.filter(r=>r.label!==1)} fill="#ef4444" name="Loss" /></ScatterChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Score Quality Trend" />{ad.score_quality_trend?.length?<ResponsiveContainer width="100%" height={250}><ComposedChart data={ad.score_quality_trend.map(r=>({...r,day:r.day?new Date(r.day).toLocaleDateString('en',{month:'2-digit',day:'2-digit'}):''}))}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="day" stroke="#64748b" fontSize={10} /><YAxis yAxisId="left" stroke="#64748b" fontSize={10} /><YAxis yAxisId="right" orientation="right" stroke="#eab308" fontSize={10} tickFormatter={v=>`${v}%`} /><Tooltip content={<ChartTT />} /><Legend /><Bar yAxisId="left" dataKey="n_signals" name="Signals" fill="#334155" /><Line yAxisId="right" type="monotone" dataKey="win_rate" name="Win Rate %" stroke="#eab308" strokeWidth={2} dot={false} /><Line yAxisId="left" type="monotone" dataKey="avg_score" name="Avg Score" stroke="#6366f1" strokeWidth={2} dot={false} /></ComposedChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card></div>)}

        {tab==='correlation'&&(<div className="space-y-6"><Card><CardHeader title="Feature Importance (Full)" subtitle="Weighted + raw correlation with outcome" />{ad.feature_importance_full?.length?<DataTable columns={[{key:'feature',header:'Feature',sortable:true},{key:'avg_contrib',header:'Avg Contrib',sortable:true,align:'right'},{key:'corr_weighted',header:'Corr (wt)',sortable:true,align:'right',render:v=><span className={Number(v)>=0?'text-emerald-400':'text-red-400'}>{v}</span>},{key:'corr_raw',header:'Corr (raw)',sortable:true,align:'right',render:v=><span className={Number(v)>=0?'text-emerald-400':'text-red-400'}>{v}</span>},{key:'n',header:'N',align:'right'}]} data={ad.feature_importance_full} pageSize={10} />:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Feature Importance Chart" />{ad.feature_importance_full?.length?<ResponsiveContainer width="100%" height={250}><BarChart data={[...(ad.feature_importance_full||[])].sort((a,b)=>Math.abs(Number(b.corr_raw))-Math.abs(Number(a.corr_raw)))} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis type="number" stroke="#64748b" fontSize={11} /><YAxis type="category" dataKey="feature" stroke="#64748b" fontSize={11} width={80} /><Tooltip content={<ChartTT />} /><Bar dataKey="corr_raw" name="Corr (raw)" radius={[0,4,4,0]}>{[...(ad.feature_importance_full||[])].sort((a,b)=>Math.abs(Number(b.corr_raw))-Math.abs(Number(a.corr_raw))).map((e,i)=><Cell key={i} fill={Number(e.corr_raw)>=0?'#10b981':'#ef4444'} />)}</Bar></BarChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <Card><CardHeader title="Correlation Matrix" subtitle="Feature-to-feature & outcome" />{ad.feature_correlation?.length?(()=>{const fields=['trend_score','momentum_score','volume_score','pattern_score','mtf_score','penalty_norm','total_score','outcome'];const names={trend_score:'Trend',momentum_score:'Mom',volume_score:'Vol',pattern_score:'Pat',mtf_score:'MTF',penalty_norm:'Pen',total_score:'Total',outcome:'Outcome'};const data=ad.feature_correlation.filter(r=>fields.every(f=>r[f]!=null&&!isNaN(Number(r[f]))));if(data.length<5)return<div className="h-48 flex items-center justify-center text-slate-500">Insufficient data ({data.length} rows)</div>;const n=data.length;const means={};fields.forEach(f=>means[f]=data.reduce((s,r)=>s+Number(r[f]),0)/n);const hm=[];fields.forEach(fy=>fields.forEach(fx=>{let cov=0,sx=0,sy=0;data.forEach(r=>{const dx=Number(r[fx])-means[fx];const dy=Number(r[fy])-means[fy];cov+=dx*dy;sx+=dx*dx;sy+=dy*dy;});const den=Math.sqrt(sx)*Math.sqrt(sy);const corr=den>0?cov/den:0;hm.push({x:names[fx],y:names[fy],value:Math.round(corr*100),count:n});}));return<Heatmap data={hm} xLabel="" yLabel="" valueLabel="Corrx100" colorScale="blue-orange" showValues />;})():<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card></div>)}

        {tab==='indicators'&&(<div className="space-y-6"><div className="grid grid-cols-1 md:grid-cols-3 gap-6"><Card><CardHeader title="RSI Buckets" />{ad.indRsi?.length?<DataTable columns={[{key:'bucket',header:'RSI'},{key:'trades',header:'Trades',sortable:true,align:'right'},{key:'win_rate',header:'WR%',sortable:true,align:'right',render:v=><span className={v>=50?'text-emerald-400':'text-red-400'}>{v}%</span>},{key:'avg_return',header:'Avg Ret',sortable:true,align:'right'}]} data={ad.indRsi} pageSize={10} />:<div className="h-32 flex items-center justify-center text-slate-500">No data</div>}</Card><Card><CardHeader title="Volume Ratio Buckets" />{ad.indVol?.length?<DataTable columns={[{key:'bucket',header:'Vol Ratio'},{key:'trades',header:'Trades',sortable:true,align:'right'},{key:'win_rate',header:'WR%',sortable:true,align:'right',render:v=><span className={v>=50?'text-emerald-400':'text-red-400'}>{v}%</span>},{key:'avg_return',header:'Avg Ret',sortable:true,align:'right'}]} data={ad.indVol} pageSize={10} />:<div className="h-32 flex items-center justify-center text-slate-500">No data</div>}</Card><Card><CardHeader title="ATR Percentile" />{ad.indAtr?.length?<DataTable columns={[{key:'bucket',header:'ATR %'},{key:'trades',header:'Trades',sortable:true,align:'right'},{key:'win_rate',header:'WR%',sortable:true,align:'right',render:v=><span className={v>=50?'text-emerald-400':'text-red-400'}>{v}%</span>},{key:'avg_return',header:'Avg Ret',sortable:true,align:'right'}]} data={ad.indAtr} pageSize={10} />:<div className="h-32 flex items-center justify-center text-slate-500">No data</div>}</Card></div>
        <Card><CardHeader title="MAE vs MFE Scatter" subtitle="SL too widex TP too closex" />{ad.maeMfe?.length?<ResponsiveContainer width="100%" height={300}><ScatterChart><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis type="number" dataKey="mae" name="MAE %" stroke="#64748b" fontSize={11} /><YAxis type="number" dataKey="mfe" name="MFE %" stroke="#64748b" fontSize={11} /><Tooltip content={<ChartTT />} /><Scatter data={ad.maeMfe.filter(r=>r.label===1)} fill="#10b981" name="Win" /><Scatter data={ad.maeMfe.filter(r=>r.label!==1)} fill="#ef4444" name="Loss" /></ScatterChart></ResponsiveContainer>:<div className="h-48 flex items-center justify-center text-slate-500">No data</div>}</Card>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6"><Card><CardHeader title="Exit Reason Breakdown" />{ad.exit_reason_breakdown?.length?<DataTable columns={[{key:'exit_reason',header:'Reason',sortable:true},{key:'count',header:'Count',sortable:true,align:'right'},{key:'pct',header:'%',sortable:true,align:'right',render:v=>`${v}%`}]} data={ad.exit_reason_breakdown} pageSize={10} />:<div className="h-32 flex items-center justify-center text-slate-500">No data</div>}</Card><Card><CardHeader title="Time to Exit" />{ad.time_to_exit_dist?.length?<ResponsiveContainer width="100%" height={200}><BarChart data={ad.time_to_exit_dist}><CartesianGrid strokeDasharray="3 3" stroke="#334155" /><XAxis dataKey="bucket" stroke="#64748b" fontSize={11} /><YAxis stroke="#64748b" fontSize={11} /><Tooltip content={<ChartTT />} /><Bar dataKey="count" name="Count" fill="#6366f1" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer>:<div className="h-32 flex items-center justify-center text-slate-500">No data</div>}</Card></div>
        </div>)}

        {tab==='trades'&&<Card><CardHeader title="Trade List" subtitle={`${tradesData.total} trades - Page ${tradesData.page} of ${tradesData.pages}`} /><DataTable columns={tradeColumns} data={tradesData.data} pageSize={20} pagination={{total:tradesData.total,page:tradesData.page,limit:tradesData.limit,pages:tradesData.pages,onPageChange:setTradesPage}} /></Card>}
      </TabContent>
    </div>
  );
}
